// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import FormController from "./form_controller"
// application.register("form", FormController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
import FlashController from "./flash_controller"
application.register("flash", FlashController)
